
'use client';

import { useState, useRef, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Bot, User, Loader2, Send } from 'lucide-react';
import { cn } from '@/lib/utils';
import { chatAssistantFlow } from '@/ai/flows/chat-flow';
import { useToast } from '@/hooks/use-toast';
import type { MessageData, ToolRequestPart, ToolResponsePart } from 'genkit';
import { useAuth } from '@/hooks/use-auth';
import { Skeleton } from '@/components/ui/skeleton';
import { useRouter } from 'next/navigation';
import Header from '@/components/Header';
import { addScheduleItem } from '@/lib/client-actions';
import { format } from 'date-fns';

type ChatMessage = {
  role: 'user' | 'model';
  content: string; 
  data?: any;
};

export default function AssistantPage() {
  const [input, setInput] = useState('');
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const scrollAreaRef = useRef<HTMLDivElement>(null);
  const { toast } = useToast();
  const { user, loading: authLoading } = useAuth();
  const router = useRouter();

  useEffect(() => {
    if (!authLoading && !user) {
      router.push('/login');
    }
  }, [user, authLoading, router]);


  useEffect(() => {
    if (scrollAreaRef.current) {
      scrollAreaRef.current.scrollTop = scrollAreaRef.current.scrollHeight;
    }
  }, [messages, isLoading]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isLoading || !user) return;

    const userMessage: ChatMessage = { role: 'user', content: input };
    setMessages(prev => [...prev, userMessage]);
    setInput('');
    setIsLoading(true);

    try {
        const history: MessageData[] = [...messages, userMessage].map(
            (msg): MessageData => ({
            role: msg.role,
            content: [{ text: msg.content }],
            })
        );
        
        let response = await chatAssistantFlow({ userId: user.uid, history });
        
        let toolRequest: ToolRequestPart | undefined = response.content.find(
            (part: any): part is ToolRequestPart => part.toolRequest !== undefined
        );

        if (toolRequest) {
            // Append the model's request and an empty response to history
            history.push(response);
            const toolResponse: MessageData = {
                role: 'tool',
                content: [{
                    toolResponse: {
                        name: toolRequest.toolRequest.name,
                        // The actual output is generated by the tool on the server
                        output: { success: true, message: `Tool ${toolRequest.toolRequest.name} called.` },
                    }
                }]
            };
            history.push(toolResponse);
            
            // Call flow again with tool context
            response = await chatAssistantFlow({ userId: user.uid, history });
        }

        const modelMessage: ChatMessage = { 
            role: 'model', 
            content: response.text,
            data: response.content.find((part: any) => part.data)?.data,
        };
        setMessages(prev => [...prev, modelMessage]);

    } catch (error: any) {
      console.error("Chat assistant error:", error);
      toast({
        variant: 'destructive',
        title: 'Chat Error',
        description: error.message || 'Sorry, I encountered an issue. Please try again.',
      });
      // Revert user message on error
      setMessages(prev => prev.slice(0, -1));
    } finally {
      setIsLoading(false);
    }
  };
  
  const handleScheduleSuggestion = async (slot: any) => {
     if (!user) return;
     try {
        await addScheduleItem({
            userId: user.uid,
            title: slot.task,
            date: slot.date,
            startTime: slot.startTime,
            endTime: slot.endTime,
            duration: slot.duration,
            type: 'event',
            icon: 'CalendarPlus',
            color: 'hsl(262.1 83.3% 57.8%)',
        });
        toast({ title: "Event Scheduled!", description: `"${slot.task}" has been added to your calendar.` });
        
        // Remove suggestions after one is picked
        setMessages(prev => {
            return prev.map(msg => {
                if (msg.data?.suggestions) {
                    return { ...msg, data: { ...msg.data, suggestions: [] } };
                }
                return msg;
            });
        });

     } catch(e) {
        toast({ variant: 'destructive', title: 'Scheduling Failed', description: 'Could not add the event to your calendar.' });
     }
  }

  if (authLoading || !user) {
    return (
      <div className="flex h-screen w-full items-center justify-center">
        <Skeleton className="h-24 w-24 rounded-full" />
      </div>
    );
  }

  return (
    <div className="flex h-svh flex-col">
      <Header />
      <main className="flex-1 flex flex-col overflow-hidden">
        <div className="flex-1 overflow-hidden flex flex-col">
           <ScrollArea className="flex-1 p-4" ref={scrollAreaRef as any}>
              <div className="space-y-6 max-w-4xl mx-auto w-full">
                {messages.map((message, index) => (
                    <div
                      key={index}
                      className={cn(
                        'flex items-start gap-4',
                        message.role === 'user' ? 'justify-end' : 'justify-start'
                      )}
                    >
                      {message.role === 'model' && <Bot className="flex-shrink-0 text-primary size-8" />}
                      <div
                        className={cn(
                          'max-w-[80%] rounded-lg px-4 py-3 text-sm md:text-base',
                          message.role === 'user'
                            ? 'bg-primary text-primary-foreground'
                            : 'bg-muted'
                        )}
                      >
                       <p>{message.content}</p>
                       {message.data?.suggestions && message.data.suggestions.length > 0 && (
                            <div className="mt-4 space-y-2">
                                <p className="font-semibold text-sm">Here are some suggestions:</p>
                                <div className="flex flex-wrap gap-2">
                                    {message.data.suggestions.map((slot: any, i: number) => (
                                        <Button key={i} size="sm" variant="outline" onClick={() => handleScheduleSuggestion(slot)}>
                                            {format(new Date(slot.date + 'T00:00:00'), 'd MMM')}, {slot.startTime}
                                        </Button>
                                    ))}
                                </div>
                            </div>
                       )}
                      </div>
                      {message.role === 'user' && <User className="flex-shrink-0 size-8" />}
                    </div>
                ))}
                {isLoading && (
                   <div className="flex items-start gap-4 justify-start">
                        <Bot className="flex-shrink-0 text-primary size-8" />
                        <div className="bg-muted rounded-lg px-4 py-3 text-sm flex items-center">
                            <Loader2 className="h-5 w-5 animate-spin" />
                        </div>
                   </div>
                )}
              </div>
            </ScrollArea>

            <div className="border-t p-4 bg-background">
                <div className="max-w-4xl mx-auto">
                    <form onSubmit={handleSubmit} className="flex w-full items-center gap-4">
                    <Input
                        value={input}
                        onChange={(e) => setInput(e.target.value)}
                        placeholder="Ask me to schedule a meeting for tomorrow at 2pm..."
                        className="flex-1 h-12 text-base"
                        disabled={isLoading}
                    />
                    <Button type="submit" size="lg" disabled={isLoading || !input.trim()}>
                        <Send className="h-5 w-5" />
                        <span className="sr-only">Send</span>
                    </Button>
                    </form>
                </div>
            </div>
        </div>
      </main>
    </div>
  );
}
